import Head from "next/head";
import useSWR from "swr";
import MovieCard from "../../components/MovieCard";

export default function Home() {
  // API URL incl Key
  const query = "Volcano";
  const api_key = "bfec423d56be8f848e042b16b5c9ad74";
  const api_url = "https://api.themoviedb.org/3/";
  const base_url = `${api_url}search/movie?query=${query}&api_key=${api_key}`;
  const imagePath = `${api_url}configuration?&api_key=${api_key}`;

  const {
    data: movieData,
    error: movieError,
    isLoading: movieLoading,
  } = useSWR(base_url);

  const {
    data: imageData,
    error: imageError,
    isLoading: imageLoading,
  } = useSWR(imagePath);

  if (imageLoading || movieLoading) {
    return "Loading...";
  }

  if (imageError || movieError) {
    return error.massage;
  }
  return (
    <>
      <Head>
        <title>Powered by Martin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>MetaMovie</h1>
        <form>
          <input type="text" name="search" id="search"></input>
          <button type="submit">Search</button>
        </form>
        <section className="movie-list">
          <MovieCard movieData={movieData} imageData={imageData} />
        </section>
      </main>
    </>
  );
}
