import MovieCard from "@/components/MovieCard";
import useSWR from "swr";
import Head from "next/head";

export default function Home() {
  // API URL incl Key
  const query = "Ingeborg";
  const api_key = "bfec423d56be8f848e042b16b5c9ad74";
  const api_url = "https://api.themoviedb.org/3/";
  const base_url = `${api_url}search/movie?query=${query}&api_key=${api_key}`;

  const imagePath = `${api_url}configuration?&api_key=${api_key}`;
  const {
    data: imageData,
    error: imageError,
    isLoading: imageLoading,
  } = useSWR(imagePath);
  const {
    data: movData,
    error: movError,
    isLoading: movLoading,
  } = useSWR(base_url);

  // console.log(movData);

  if (imageError || movError) {
    return error.massage;
  }

  if (imageLoading || movLoading) {
    return "Loading...";
  }

  return (
    <>
      <Head>
        <title>Meta Movie - Powered by Martin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Meta-Movie</h1>
        <form>
          <input type="text" name="search" id="search"></input>
          <button type="submit">Search</button>
        </form>
        <section className="movie-list">
          <MovieCard movieData={movData} imageData={imageData} />
        </section>
      </main>
    </>
  );
}
